name: Update Data

on: push

jobs:
  fetch_data:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3'
          bundler-cache: true

      - name: Generate Data
        run: ./bin/generate_data

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.REPO_TOKEN }}
          commit-message: "Update contact data"
          title: "Update contact data"
          labels: "update_data"
          base: "master"
